version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong!Pass123"
      ACCEPT_EULA: "Y"
    networks:
      - banknet

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fitzbank-api
    ports:
      - "8080:8080"                         # 👈 наружу:внутрь
    depends_on:
      - db
    environment:
      ASPNETCORE_URLS: "http://+:8080"      # 👈 внутри контейнера слушаем 8080
      ASPNETCORE_ENVIRONMENT: "Development" # чтобы Swagger точно рисовался (хоть мы и включили всегда)
      ConnectionStrings__DefaultConnection: "Server=db;Database=BankingDb;User=sa;Password=YourStrong!Pass123;TrustServerCertificate=True"
    networks:
      - banknet

networks:
  banknet:
